### ISSUE TITLE
Can not find moudles that have parameters when instantiate.

### ISSUE THREAD

**Issue by DavidZyy** [Nitcloud/Digital-IDE#55]
![image](https://user-images.githubusercontent.com/68588633/218393434-9c13571a-810a-475b-979f-85c27b8d990b.png)

**Comment by DavidZyy** [comment]
![image](https://user-images.githubusercontent.com/68588633/218393644-6d6995d6-0a27-4768-94b7-b2ae9dfdd7a7.png)
When I want to instatiate a moudle like this that has parameters, I can not find it in the list.

**Comment by Nitcloud** [comment]
define paramters like this:
paramter WIDTH = 1

Yangyang Zhu ***@***.***> 于2023年2月13日周一 15:13写道：

**Comment by DavidZyy** [comment]
It works, thank you!
