### ISSUE TITLE
在插件中使用vivado仿真波形无变化

### ISSUE THREAD

**Issue by fusheng-lei** [Nitcloud/Digital-IDE#84]

**Comment by ziky0827** [comment]
![%TUXREI~_0I~UEUJ26`XW%N](https://github.com/Nitcloud/Digital-IDE/assets/61941340/1337ec8c-0759-47ff-b285-5eb5d436911f)
![FQ2YY@U3 R C@VYJLDD_HCW](https://github.com/Nitcloud/Digital-IDE/assets/61941340/997e860c-a352-418d-920d-c251cc2b63d7)
![J_S3 SX_6LX7$)PAV0A)1LR](https://github.com/Nitcloud/Digital-IDE/assets/61941340/5835d6c8-8e59-434b-a7f5-f9b6585c7d91)
![JQW(EW$%D7Y}C)X %@SCMMF](https://github.com/Nitcloud/Digital-IDE/assets/61941340/46b05e3c-2f0e-4de6-a76d-a725385a85bf)
![NJTA92)SON8PR2{$}P@)`68](https://github.com/Nitcloud/Digital-IDE/assets/61941340/0907b29f-1e74-4084-97e8-3db3db679c79)
